- id: '1670688318358'
  alias: Wohnzimmerlampe ein-/ausschalten
  description: Wohnzimmerlampe ein-/ausschalten, wenn Shortcut Button einmal gedrückt
    wird
  trigger:
  - device_id: 47e8f828bb3bb1c741b029485013a88e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 6a215cd52677eb61f0e14699b1550498
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_switch
    domain: switch
  mode: single
- id: '1670688833151'
  alias: Wohnzimmerlampe bei Sonnenuntergang einschalten
  description: Schaltet die Wohnzimmerlampe bei Sonnenuntergang ein, falls es vor
    22 Uhr ist.
  trigger:
  - platform: sun
    event: sunset
    offset: '-600'
  condition:
  - condition: time
    before: '22:00:00'
  - condition: device
    type: is_off
    device_id: 6a215cd52677eb61f0e14699b1550498
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_switch
    domain: switch
  - condition: state
    entity_id: binary_sensor.someone_home
    state: 'on'
  action:
  - type: turn_on
    device_id: 6a215cd52677eb61f0e14699b1550498
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_switch
    domain: switch
  mode: single
- id: '1670692140117'
  alias: Rolläden vollständig öffnen mit Fernbedienung
  description: Öffnet die Rolläden vollständig, wenn die Einschalttaste der Fernbedienung
    kurz gedrückt wird
  trigger:
  - device_id: e464a5a9bd9835b772adce825d27f4af
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - device_id: 1225fad3bdd18d0f82cac36db43936d2
    domain: cover
    entity_id: cover.rolladen_balkon_rechts
    type: set_position
    position: 100
  - device_id: b636ac782ee3b6e565cedc9361c6a948
    domain: cover
    entity_id: cover.shellyswitch25_4c752533d2c4
    type: set_position
    position: 100
  mode: single
- id: '1670692254470'
  alias: Rollläden vollständig schließen mit Fernbedienung
  description: Schließt die Rolläden vollständig, wenn die Ausschalttaste der Fernbedienung
    kurz gedrückt wird.
  trigger:
  - device_id: e464a5a9bd9835b772adce825d27f4af
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - device_id: 1225fad3bdd18d0f82cac36db43936d2
    domain: cover
    entity_id: cover.rolladen_balkon_rechts
    type: set_position
    position: 0
  - device_id: b636ac782ee3b6e565cedc9361c6a948
    domain: cover
    entity_id: cover.shellyswitch25_4c752533d2c4
    type: set_position
    position: 0
  mode: single
- id: '1670694804524'
  alias: Licht einschalten, wenn jemand nach Hause kommt
  description: Schaltet manche Lichter an, wenn jemand nach Hause kommt
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  - condition: time
    before: input_datetime.schlafenszeit
    after: 08:00:00
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.flur_licht
      - light.wohnzimmer_licht_tur
      - light.wohnzimmerlampe
  mode: single
- id: '1670763004553'
  alias: Heizung bei offenem Fenster ausschalten
  description: Schaltet die Heizung in dem Zimmer aus, in dem ein offenes Fenster
    erkannt wurde
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.arbeitszimmer_open_window
    from: 'off'
    to: 'on'
    id: arbeitszimmer
  - platform: state
    entity_id:
    - binary_sensor.badezimmer_open_window
    from: 'off'
    to: 'on'
    id: badezimmer
  - platform: state
    entity_id:
    - binary_sensor.wohnzimmer_open_window
    from: 'off'
    to: 'on'
    id: wohnzimmer
  condition:
  - condition: state
    entity_id: binary_sensor.warm_inside
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: arbeitszimmer
      sequence:
      - device_id: 205df024614b863140e76ffee6f8146e
        domain: climate
        entity_id: climate.arbeitszimmer
        type: set_hvac_mode
        hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: badezimmer
      sequence:
      - device_id: 0399e671c3e0d78d294619d3cd89639f
        domain: climate
        entity_id: climate.badezimmer
        type: set_hvac_mode
        hvac_mode: 'off'
    - conditions:
      - condition: trigger
        id: wohnzimmer
      sequence:
      - device_id: c587d6d3d2c00b478dc8e35e8ff65e11
        domain: climate
        entity_id: climate.wohnzimmer
        type: set_hvac_mode
        hvac_mode: 'off'
  mode: single
- id: '1670765446255'
  alias: Heizung einschalten, wenn Fenster geschlossen wird
  description: Schaltet die Heizung in dem Zimmer ein, in dem ein offenes Fenster
    geschlossen wurde
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.arbeitszimmer_open_window
    from: 'on'
    to: 'off'
    id: arbeitszimmer
  - platform: state
    entity_id:
    - binary_sensor.badezimmer_open_window
    from: 'on'
    to: 'off'
    id: badezimmer
  - platform: state
    entity_id:
    - binary_sensor.wohnzimmer_open_window
    from: 'on'
    to: 'off'
    id: wohnzimmer
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: arbeitszimmer
      sequence:
      - device_id: 205df024614b863140e76ffee6f8146e
        domain: climate
        entity_id: climate.arbeitszimmer
        type: set_hvac_mode
        hvac_mode: auto
    - conditions:
      - condition: trigger
        id: badezimmer
      sequence:
      - device_id: 0399e671c3e0d78d294619d3cd89639f
        domain: climate
        entity_id: climate.badezimmer
        type: set_hvac_mode
        hvac_mode: auto
    - conditions:
      - condition: trigger
        id: wohnzimmer
      sequence:
      - device_id: c587d6d3d2c00b478dc8e35e8ff65e11
        domain: climate
        entity_id: climate.wohnzimmer
        type: set_hvac_mode
        hvac_mode: auto
  mode: single
- id: '1670775293197'
  alias: Heizung ausschalten, wenn niemand Zuhause ist
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id:
      - arbeitszimmer
      - badezimmer
      - wohnzimmer
  mode: single
- id: '1670775647819'
  alias: Heizung einschalten, wenn jemand nach Hause kommt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    to: 'on'
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: home
    target:
      area_id:
      - arbeitszimmer
      - badezimmer
      - wohnzimmer
  mode: single
- id: '1671392941932'
  alias: Licht ausschalten, wenn keiner Zuhause ist
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - arbeitszimmer
      - badezimmer
      - flur
      - kuche
      - schlafzimmer
      - terrasse
      - wohnzimmer
  mode: single
- id: '1671725896947'
  alias: Urlaubsmodus aktivieren
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.urlaubsmodus
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
      - automation.wohnzimmerlampe_bei_sonnenuntergang_einschalten
      - automation.rolladen_bei_sonnenaufgang_offnen
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id:
      - arbeitszimmer
      - badezimmer
      - wohnzimmer
  mode: single
- id: '1671726553452'
  alias: Urlaubsmodus aus
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.urlaubsmodus
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: automation.turn_on
    data: {}
    target:
      entity_id:
      - automation.wohnzimmerlampe_bei_sonnenuntergang_einschalten
      - automation.rolladen_bei_sonnenaufgang_offnen
  - service: automation.trigger
    data:
      skip_condition: false
    target:
      entity_id:
      - automation.update_notifications
      - automation.wohnzimmerlampe_bei_sonnenuntergang_einschalten
  mode: single
- id: '1671726673420'
  alias: Urlaubsmodus deaktivieren, wenn jemand nach Hause kommt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.someone_home
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.urlaubsmodus
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.urlaubsmodus
  mode: single
- id: '1674716584358'
  alias: Wohnzimmerlampe nachts ausschalten
  description: Schalte die Wohnzimmerlampe nachts um 12:00 Uhr aus
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: device
    type: is_on
    device_id: 6a215cd52677eb61f0e14699b1550498
    entity_id: light.wohnzimmerlampe
    domain: light
  action:
  - type: turn_off
    device_id: 6a215cd52677eb61f0e14699b1550498
    entity_id: light.wohnzimmerlampe
    domain: light
  mode: single
- id: '1711921509982'
  alias: Rolläden bei Sonnenaufgang öffnen
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  - platform: time
    at: 06:00:00
  - platform: time
    at: 07:00:00
  condition:
  - condition: or
    conditions:
    - condition: device
      device_id: 1225fad3bdd18d0f82cac36db43936d2
      domain: cover
      entity_id: 1e3c8d2dfa655b8b526ff3b5ec8e9bfa
      type: is_closed
    - condition: device
      device_id: b636ac782ee3b6e565cedc9361c6a948
      domain: cover
      entity_id: e18dcea846aa2b3cd228c33c39b4450c
      type: is_closed
  - condition: or
    conditions:
    - condition: time
      after: 07:00:00
    - condition: and
      conditions:
      - condition: sun
        after: sunrise
      - condition: time
        after: 06:00:00
  action:
  - device_id: 1225fad3bdd18d0f82cac36db43936d2
    domain: cover
    entity_id: 1e3c8d2dfa655b8b526ff3b5ec8e9bfa
    type: open
  - device_id: b636ac782ee3b6e565cedc9361c6a948
    domain: cover
    entity_id: e18dcea846aa2b3cd228c33c39b4450c
    type: open
  mode: single
- id: '1742400859847'
  alias: Benachrichtigung bei Raspberry Pi Stromproblem
  description: Sendet eine Benachrichtigung, wenn der Raspberry Pi ein Stromversorgungsproblem
    erkennt.
  triggers:
  - entity_id: binary_sensor.rpi_power_status
    to: 'on'
    trigger: state
  conditions: []
  actions:
  - data:
      title: ⚠️ Home Assistant Stromproblem
      message: Dein Raspberry Pi hat ein Stromversorgungsproblem! Bitte überprüfe
        das Netzteil.
      data:
        ttl: 0
        priority: high
    action: notify.mobile_app_pixel_6a
  - data:
      title: Raspberry Pi Stromversorgungsproblem
      message: Es wurde ein Unterspannungs- oder Stromproblem erkannt. Bitte überprüfe
        dein Netzteil.
    action: persistent_notification.create
  - delay: 00:05:00
  - condition: state
    entity_id: binary_sensor.rpi_power_status
    state: 'on'
  - action: homeassistant.restart
    data: {}
  mode: single
- id: '1742738781476'
  alias: Benachrichtigung senden bei erhalt eines Kuma Alarms
  description: Sendet eine Benachrichtigung bei Erhalt eines Kuma Service Alarms
  triggers:
  - webhook_id: kuma_alert
    trigger: webhook
  actions:
  - action: notify.mobile_app_pixel_6a
    data:
      title: ⚠️ Smart Home Service Alarm!
      message: '{{ trigger.json.message }}'
      data:
        ttl: 0
        priority: high
  mode: single
