- platform: template
  sensors:
    warm_inside:
      friendly_name: "Wohnungstemperatur ist höher als Außentemperatur"
      value_template: "{{ states('sensor.durchschnittliche_wohnungstemperatur') | float(0) >= state_attr('weather.zuhause', 'temperature') }}"

- platform: template
  sensors:
    someone_home:
      friendly_name: Jemand Zuhause
      device_class: presence
      value_template: "{{ states.person | selectattr('state', 'eq', 'home') | list | count > 0 }}"
